<?php
/**
 * My Copyright © to Magento.
 */
?>
<small class="copyright">
    <span>
        This is my © from <?php echo date("Y"); ?>. Task 3
    </span>
</small>
<h2>Read More, Read Less Button ( Task 3.a.b )</h2>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus imperdiet, nulla et dictum interdum, nisi lorem egestas vitae scel<span id="dots">...</span>
    <span id="more" data-mage-init='{"hello": {"text": "erisque enim ligula venenatis dolor. Maecenas nisl est, ultrices nec congue eget, auctor vitae massa. Fusce luctus vestibulum augue ut aliquet. Nunc sagittis dictum nisi, sed ullamcorper ipsum dignissim ac. In at libero sed nunc venenatis imperdiet sed ornare turpis. Donec vitae dui eget tellus gravida venenatis. Integer fringilla congue eros non fermentum. Sed dapibus pulvinar nibh tempor porta."}}'></span>
</p>
<button id="myBtn">Read more</button>
